nano /etc/resolv.conf
#сопировать содержимое
domain Wireless-N
search Wireless-N
nameserver 8.8.8.8


nano /etc/resolv.conf
rm -f /etc/resolv.conf
nano /etc/resolv.conf
#вставить содержимое


chattr +i /etc/resolv.conf


#MTS
nameserver 212.188.4.10

nameserver 192.168.1.1
options edns0 trust-ad
search Wireless-N

nameserver 8.8.8.8
options edns0 trust-ad
search .



# Generated by NetworkManager
search HA
nameserver 8.8.8.8


Киров
212.188.4.10
195.34.32.116